### PR TITLE
feat: add addslice button to selection predicates

### PR DESCRIPTION
**Pull request by Sparkier**
# Description

image

fix ZEN-226

### CODE REVIEW

**Comment by cabreraalex** [comment]
should we make it purple?

**Comment by Sparkier** [comment]
You mean making it `raised`?

**Comment by cabreraalex** [comment]
or unelevated

**Comment by cabreraalex** [comment]
also if we put it here should we remove it from the other place? or okay in both?

**Comment by Sparkier** [comment]
Don't know, looks a bit weird to me:
image

**Comment by Sparkier** [comment]
> from

Was thinking about this as well. Don't know what one would expect. It does not really hurt to have it in both places right?

**Comment by cabreraalex** [comment]
okay maybe white bg and keep both

**Review by cabreraalex — APPROVED** [review]

**Pull request merged**
