### PR TITLE
fix: fix backend warnings

### PR DESCRIPTION
**Pull request by Sparkier**

### CODE REVIEW

**Comment by cabreraalex** [comment]
This looks like two separate PRs?

**Comment by Sparkier** [comment]
Hmm it's all mainly to silence warnings when running the backend.

**Comment by Sparkier** [comment]
What would you separate out?

**Comment by cabreraalex** [comment]
The system-name stuff from the --factory and removing the run server stuff but no worries it's fine

**Comment by cabreraalex** [comment]
integration tests might actually be doing something?

**Comment by cabreraalex** [comment]
Did some debugging - this breaks because slices are stored with "modelName" in the database so existing project slices fail to render the model.

INTEGRATION TESTS WORK!

**Comment by cabreraalex** [comment]
idk how to fix, or if it's worth the name refactor

**Pull request closed without merging**
