### PR TITLE
feat: show a preview of the charts in the chart overview

### PR DESCRIPTION
**Pull request by Sparkier**
# Description

image

fix ZEN-391

### CODE REVIEW

**Comment by Sparkier** [comment]
Don't understand the linter errors, I don't get them locally.

**Comment by Sparkier** [comment]
ping @cabreraalex

**Comment by cabreraalex** [comment]
Honestly think it looks pretty rough with the huge fonts, crunched up legends, etc... idk if we actually want this? what do you think?

**Comment by Sparkier** [comment]
There shouldn't be any legends visible in the previews. Don't know if you had the right version.

**Comment by Sparkier** [comment]
Ah the screenshot is outdated btw.

**Comment by Sparkier** [comment]
Actually, I pushed something wrong, but looks like this:

CleanShot 2024-01-11 at 09 57 35

**Comment by Sparkier** [comment]
Could think about removing all the axis labels and text but generally this makes it so much easier to find the chart you're looking for.

**Comment by Sparkier** [comment]
We'll probably have to fix some things once it's deployed but I'd say it's already much better than what we had.

**Comment by cabreraalex** [comment]
Alright yeah it had't updated locally for some reason. It looks good to me, one worry is if you have dozens of charts it could slow down to load, maybe we add infinite scroll or pagination as a todo?

**Comment by Sparkier** [comment]
sgtm, testing speed locally is kinda hard so not sure about it. One thing is that the charts are loaded async anyway I think so that might help.

**Review by cabreraalex — APPROVED** [review]

**Pull request merged**
