### PR TITLE
feat: add delete confirmation popup when deleting something

### PR DESCRIPTION
**Pull request by Sparkier**
fix ZEN-230

### CODE REVIEW

**Comment by cabreraalex** [comment]
do we want this for slices, tags, and report elements? Can be a bit annoying if you are deleting a bunch in a row. but maybe worth it?

**Comment by Sparkier** [comment]
Was thinking the same and don't have a definitive answer. One hand can be annoying, other hand if you delete something accidentally from a report by clicking the X this can be pretty devastating.

**Comment by Sparkier** [comment]
Same for carefully curated slices and tags.

**Comment by cabreraalex** [comment]
Okay, LGTM. We can add a "don't ask again" button eventually lol

**Review by cabreraalex — APPROVED** [review]

**Pull request merged**
