### PR TITLE
feat: add matching secondary color

### PR DESCRIPTION
**Pull request by Sparkier**
# Description

To me, the teal color does not work well with the purple. Could just be me but I think color theory supports my thinking.

The teal is not [complimentary](https://www.sessions.edu/color-calculator-results/?colors=6a1b9a,9a831b) or [related in any other way to the purple](https://www.sessions.edu/color-calculator-results/?colors=6a1b9a,9a1b8b,2a1b9a).

Since we're talking about something like a secondary color, I think an analogous harmony would work well. I picked the [blue here](https://www.sessions.edu/color-calculator-results/?colors=6a1b9a,9a1b8b,2a1b9a) for now which I think looks good.

Happy to discuss further, though.

### CODE REVIEW

**Comment by cabreraalex** [comment]
Agreed on color, but this looks a bit too similar to purple, I barely noticed they were different?

**Comment by cabreraalex** [comment]
Screenshot 2023-11-16 at 08 40 55

**Comment by Sparkier** [comment]
Yeah they're not super different esp. the light versions we use there...

**Comment by Sparkier** [comment]
how did you get to this? I always paste the existing purple to get another color that might work from these tools. Don't think the purple you have there is used by us, right?

**Comment by cabreraalex** [comment]
The color? I just googled complements to purple and it looked nice lol

**Comment by Sparkier** [comment]
Ahh ok I think we should use the purple we're actually using not just any purple probably.

I've been pasting color values here: https://www.sessions.edu/color-calculator/

**Comment by cabreraalex** [comment]
What about something like #e4f3ff it looks nice to me. And maybe we only have the light color for highlighting tags in the histograms and tabs, but don't do a dark version for the done button, that's just purple.

**Comment by Sparkier** [comment]
kinda like it:
image

**Pull request closed without merging**
