### PR TITLE
fix: prevent illegal project or report names by removing certain char…

### PR DESCRIPTION
**Pull request by Sparkier**
…acters and encoding the URI

fix ZEN-233

Depends on:
https://github.com/zeno-ml/zeno-client/pull/31
and
https://github.com/zeno-ml/zeno-hub/pull/302

### CODE REVIEW

**Comment by Sparkier** [comment]
Not sure if we should require the newest client version with this PR. Technically with the old one can still create breaking projects but the same is true before this commit.

**Review by cabreraalex — APPROVED** [review]

**Comment by cabreraalex** [comment]
Hmm could go either way. Annoying to force people to update and very rare bug, but we could be safe

**Comment by Sparkier** [comment]
Since we're mostly hand-holding people rn maybe we don't force them? Getting users without a burden might me more important right now than preventing this very rare bug considering the number of users we have.

**Comment by cabreraalex** [comment]
sold

**Pull request merged**
